import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Providers from "@/components/providers";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";


const font = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={font.className}>
        <Providers>
          <div className="min-h-screen flex flex-col bg-indigo-200 dark:bg-black">
            <NavBar />
            {children}
            <Footer />
          </div>

        </Providers>
      </body>
    </html>
  );
}
